version: "2"
services:
  express:
    build: .
    command: npm start
    # depends_on:
    # - mongodb
    volumes:
      - .:/src
      - /node_modules
    ports:
      - "3000:3000"
      # links:
      # - mongodb
      # mongodb:
      # image: mongo:latest
      # command: --smallfiles
      # ports:
      # - 27017:27017
